# Generated by Django 2.2.1 on 2019-10-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('ip_display', models.CharField(default='', max_length=16)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('number_of_get_request', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
