# Generated by Django 2.2.1 on 2019-08-21 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_income', models.FloatField()),
                ('m_income', models.FloatField(blank=True, null=True)),
                ('de_income', models.FloatField(blank=True, null=True)),
                ('de_amount', models.FloatField(blank=True, null=True)),
                ('na_pension', models.FloatField(blank=True, null=True)),
                ('he_insurance', models.FloatField(blank=True, null=True)),
                ('a_insurance', models.FloatField(blank=True, null=True)),
                ('em_insurance', models.FloatField(blank=True, null=True)),
                ('in_tax', models.FloatField(blank=True, null=True)),
                ('resi_tax', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('ques', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_income', models.FloatField()),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Short_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranq.Question')),
            ],
        ),
    ]
