# Generated by Django 2.2.1 on 2019-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='U_Info_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_income', models.FloatField()),
                ('rank_income', models.FloatField(blank=True, null=True)),
                ('m_income', models.FloatField(blank=True, null=True)),
                ('de_income', models.FloatField(blank=True, null=True)),
                ('de_amount', models.FloatField(blank=True, null=True)),
                ('na_pension', models.FloatField(blank=True, null=True)),
                ('he_insurance', models.FloatField(blank=True, null=True)),
                ('a_insurance', models.FloatField(blank=True, null=True)),
                ('em_insurance', models.FloatField(blank=True, null=True)),
                ('in_tax', models.FloatField(blank=True, null=True)),
                ('resi_tax', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
