# Generated by Django 2.2.1 on 2019-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0002_u_info_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_income', models.FloatField()),
                ('goal_income', models.FloatField()),
                ('period', models.FloatField()),
                ('plan_1', models.CharField(blank=True, max_length=30, null=True)),
                ('time_1', models.FloatField(blank=True, null=True)),
                ('plan_2', models.CharField(blank=True, max_length=30, null=True)),
                ('time_2', models.FloatField(blank=True, null=True)),
                ('plan_3', models.CharField(blank=True, max_length=30, null=True)),
                ('time_3', models.FloatField(blank=True, null=True)),
                ('plan_4', models.CharField(blank=True, max_length=30, null=True)),
                ('time_4', models.FloatField(blank=True, null=True)),
                ('plan_5', models.CharField(blank=True, max_length=30, null=True)),
                ('time_5', models.FloatField(blank=True, null=True)),
                ('plan_6', models.CharField(blank=True, max_length=30, null=True)),
                ('time_6', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
