# Generated by Django 2.2.1 on 2019-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0002_short_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
