# Generated by Django 2.2.1 on 2019-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0003_goal_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_income',
            name='time_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal_income',
            name='time_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal_income',
            name='time_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal_income',
            name='time_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal_income',
            name='time_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal_income',
            name='time_6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
