# Generated by Django 2.2.1 on 2019-09-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0004_auto_20190905_2330'),
        ('ranq', '0003_auto_20190816_0157'),
    ]

    operations = [
    ]
