# Generated by Django 2.2.1 on 2019-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0005_merge_20190916_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endure_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_time', models.FloatField()),
            ],
        ),
    ]
