# Generated by Django 2.2.1 on 2019-10-20 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0007_iq_answers_iq_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='endure_test',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goal_income',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='iq_answers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
