# Generated by Django 2.2.1 on 2019-10-20 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0008_auto_20191020_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank_income',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
