# Generated by Django 2.2.1 on 2019-10-20 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0009_rank_income_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_info_income',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
