# Generated by Django 2.2.1 on 2019-10-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0010_u_info_income_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_info_income',
            name='ip',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
