# Generated by Django 2.2.1 on 2019-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq', '0011_u_info_income_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='endure_test',
            name='ip',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='goal_income',
            name='ip',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='iq_answers',
            name='ip',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
